language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository

before_install:
 - chmod +x gradlew

script: ./gradlew test