language: android
jdk: oraclejdk8

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_install:
 - chmod +x gradlew

# as release version requires signature (with key from keystore)
script: ./gradlew testDebug

