package pl.rafalmag.worktimetracerlibrary.db;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.util.Date;

@DatabaseTable(tableName = "events")
public class Event {

    static final String TYPE = "TYPE";

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    protected int id;
    @DatabaseField
    protected Date date = new Date();

    @DatabaseField
    protected int version = 1;

    @DatabaseField
    protected String data = "";

    @Deprecated
    public Event() {
        this("");
    }

    public Event(String data) {
        this.data = data;
    }

    public Event(Event event) {
        this.data = event.data;
        this.date = event.date;
        this.id = event.id;
        this.version = event.version;
    }

    public int getId() {
        return id;
    }

    public Date getDate() {
        return date;
    }

    public int getVersion() {
        return version;
    }

    public String getData() {
        return data;
    }
}
