package pl.rafalmag.worktimetracerlibrary.db;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import java.util.Date;

@DatabaseTable(tableName = "events")
public class Event {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    Date date;


    public Event() {
        this.date = new Date();
    }
}
